<div>
  <table>
    <thead>
      <tr>
        <th>
          <h2><%t SilverShop\Model\Order.db_Notes "Notes" %></h2>
        </th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>$Notes</td>
      </tr>
    </tbody>
    <tfoot>
      <tr>
        <td></td>
      </tr>
    </tfoot>
  </table>
</div>
